version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/osi-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/osi-frontend"
    schedule:
      interval: "weekly"
