services:
  backend:
    build:
      context: ./osi-backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./osi-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
