name: OSI Visualizer CI for Backend and Frontend

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t osi-backend:latest -f ./osi-backend/Dockerfile.backend ./osi-backend

  build-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t osi-frontend:latest -f ./osi-frontend/Dockerfile.frontend ./osi-frontend
